KerasJson: model64_model.json
KerasH5:   model64_weights.h5

OutputDir: latency/model64_rf72

ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5
Backend: Vivado

IOType: io_serial # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 72
    Strategy: Resource
    BramFactor:    50000
    MergeFactor:   1    # compress 8 bit weights to 16 bit weights and use DSPs
#  LayerType:
#    Dense:
#      ReuseFactor: 2
#      Strategy: Resource
#      Compression: True
